fix lending trade trie & add some lending api
BuildOnViction/victionchain pull request #141
Opened 2020-02-17 03:20 UTC by nguyenbatam

2020-02-17 07:02 UTC, thanhnguyennguyen approved these changes
Looks good.
Please resolve conflict

2020-02-17 10:56 UTC, thanhnguyennguyen commented on core/order_pool_test.go
> +	_1E18      = new(big.Int).Mul(big.NewInt(10000000000000000), big.NewInt(1000))
this number is 1e19 not 1e18 :smile:

2020-02-18 02:54 UTC, thanhnguyennguyen requested changes

2020-02-18 02:54 UTC, thanhnguyennguyen commented on tomoxlending/tomoxlending.go
> +			highestPrice, liquidationData = tradingState.GetLowestLiquidationPriceData(orderbook, liquidationPrice)
GetHighestLiquidationPriceData

2020-02-18 04:44 UTC, thanhnguyennguyen approved these changes

2020-02-20 10:52 UTC, thanhson1085 approved these changes

2020-02-20 10:52 UTC, merged