verify/calculate signature payment/deposit lending transaction
BuildOnViction/victionchain pull request #168
Opened 2020-03-06 10:19 UTC by nghiatomo

2020-03-06 13:32 UTC, thanhnguyennguyen requested changes

2020-03-06 13:32 UTC, thanhnguyennguyen commented on core/types/lending_transaction.go
> +	LendingStatusPayment       = "PAYMENT"
This status is renamed to `REPAY` https://github.com/tomochain/tomochain/blob/tomoxlending/tomoxlending/lendingstate/lendingitem.go#L19

2020-03-06 13:32 UTC, thanhnguyennguyen commented on core/types/lending_transaction.go
> +	LendingStatusDeposit       = "DEPOSIT"
This status is renamed to `TOPUP` https://github.com/tomochain/tomochain/blob/tomoxlending/tomoxlending/lendingstate/lendingitem.go#L18

2020-03-09 06:32 UTC, thanhson1085 approved these changes

2020-03-09 06:32 UTC, merged