fix trading lending state
BuildOnViction/victionchain pull request #182
Opened 2020-03-14 04:44 UTC by nguyenbatam

2020-03-15 03:06 UTC, thanhnguyennguyen requested changes

2020-03-15 03:06 UTC, thanhnguyennguyen commented on core/lending_pool_test.go
>  func TestSendLending(t *testing.T) {
`t.SkipNow()` 
to skip this test in travis

2020-03-16 03:23 UTC, thanhnguyennguyen requested changes

2020-03-16 03:23 UTC, thanhnguyennguyen commented on core/order_pool_test.go
> +	for true {
tests ran too long due to this one
Please don't commit this change

2020-03-16 09:38 UTC, thanhnguyennguyen approved these changes

2020-03-16 11:07 UTC, thanhson1085 approved these changes

2020-03-16 11:08 UTC, merged