core auto recall
BuildOnViction/victionchain pull request #211
Opened 2020-03-30 04:42 UTC by nguyenbatam

2020-03-31 04:30 UTC, thanhnguyennguyen commented on tomoxlending/order_processor.go
> +		return fmt.Errorf("process deposit for emptyLendingTrade is not allowed. lendingTradeId: %v", lendingTradeId.Hex()), true, nil
update error message:
return fmt.Errorf("**processRecall** for emptyLendingTrade is not allowed. lendingTradeId: %v", lendingTradeId.Hex()), true, nil

2020-03-31 04:30 UTC, thanhnguyennguyen commented on tomoxlending/tomoxlending.go
> +							continue
no need **continue** here

2020-04-01 03:41 UTC, thanhnguyennguyen requested changes

2020-04-01 03:41 UTC, thanhnguyennguyen commented on core/lending_pool_test.go
> +	key := "65ec4d4dfbcac594a14c36baa462d6f73cd86134840f6cf7b80a1e1cd33473e2"
don't commit them

2020-04-01 03:41 UTC, thanhnguyennguyen commented on tomoxlending/order_processor.go
> +		return trades, rejects, nil
rebase mistake: remove them, please
Cancel items are processed here https://github.com/tomochain/tomochain/pull/211/files#diff-bb070402da3cf4811b1d48bdf02391e6R90

2020-04-01 10:05 UTC, thanhnguyennguyen requested changes

2020-04-01 10:05 UTC, thanhnguyennguyen commented on tomoxlending/tomoxlending.go
> +		recalLiquidatePrice = new(big.Int).Div(collateralPrice, recallRate)
recalLiquidatePrice = new(big.Int).Div(**recalLiquidatePrice**, recallRate)

2020-04-03 07:42 UTC, thanhnguyennguyen approved these changes

2020-04-05 10:45 UTC, thanhson1085 approved these changes

2020-04-05 10:46 UTC, merged